const planets = [
  {
    name: "Mercure",
    size: "4878 kms",
    spitch: `Mercure (0,4 ua) est la planète la plus proche du Soleil, ainsi que la plus petite (4 878 km de diamètre) et la moins massive avec un peu plus du vingtième de la masse terrestre97,98,99.

        Elle ne possède aucun satellite naturel et ses seules caractéristiques géologiques connues, en dehors des cratères d’impact, sont des dorsa qui ont probablement été produites par contraction thermique lors de sa solidification interne tôt dans son histoire100,101. Elle possède relativement à sa taille un très grand noyau de fer liquide — qui représenterait 85 % de son rayon, contre environ 55 % pour la Terre — et un fin manteau, ce qui n'est pas expliqué de façon certaine mais pourrait être du à un impact géant ou à l'importante température lors de son accrétion101102.
        
        Mercure a la particularité d'être en résonance spin-orbite 3:2, sa période de révolution (~88 jours) valant exactement 1,5 fois sa période de rotation (~59 jours), et donc la moitié d'un jour solaire (~176 jours)98,101. Ainsi, relativement aux étoiles fixes, elle tourne sur son axe exactement trois fois toutes les deux révolutions autour du Soleil. Par ailleurs, son orbite possède une excentricité de 0,2, soit plus de douze fois supérieure à celle de la Terre et de loin la plus élevée pour une planète du Système solaire98,101.
        
        L'atmosphère de Mercure, quasiment inexistante et qualifiable d'exosphère, est formée d’atomes arrachés à sa surface (oxygène, sodium et potassium) par le vent solaire ou momentanément capturés à ce vent (hydrogène et hélium)103100,104. Cette absence implique qu'elle n'est pas protégée des météorites et donc sa surface est très fortement cratérisée et globalement similaire à la face cachée de la Lune, car elle est géologiquement inactive depuis des milliards d'années93,101. De plus, le manque d'atmosphère combiné à la proximité du Soleil engendre d'importantes variations de la température en surface, allant de 90 K (−183 °C) au fond des cratères polaires — là où les rayons du Soleil ne parviennent jamais — jusqu'à 700 K`
  },
  {
      name: "Venus",
      size: "12104 kms",
      spitch: `Vénus (0,7 ua) est la planète la plus proche de la Terre en taille (0,95 rayon terrestre) et en masse (0,815 masse terrestre), qui lui valent d'être parfois appelée sa « planète sœur »105,106,107. Comme elle, Vénus possède un épais manteau de silicate entourant un noyau métallique, une atmosphère significative et une activité géologique internec,108. Cependant, elle est beaucoup plus sèche et la pression de son atmosphère au sol est 92 fois plus élevée109. Son importante atmosphère, composée à plus de 96 % de dioxyde de carbone, crée un très grand effet de serre qui en fait la planète la plus chaude du Système solaire par sa température de surface moyenne de 735 K (462 °C)103,108,105,110.

      La planète est également enveloppée d'une couche opaque de nuages d'acide sulfurique, hautement réfléchissants pour la lumière visible, empêchant sa surface d'être vue depuis l'espace et faisant de la planète le deuxième objet naturel le plus brillant du ciel nocturne terrestre après la Lune105. Bien que la présence d'océans d'eau liquide à sa surface par le passé soit supposée, la surface de Vénus est un paysage désertique sec et rocheux où se déroule toujours un volcanisme108,105. Comme elle ne possède pas de champ magnétique, son atmosphère est constamment appauvrie par le vent solaire et ce sont des éruptions volcaniques qui lui permettent de la réalimenter109,111. La topographie de Vénus présente peu de reliefs élevés et consiste essentiellement en de vastes plaines géologiquement très jeunes de quelques centaines de millions d'années, notamment grâce à son épaisse atmosphère la protégeant des impacts météoritiques et à son volcanisme renouvelant le sol93,112.
      
      Vénus orbite autour du Soleil tous les 224,7 jours terrestres et, avec une période de rotation de 243 jours terrestres, il lui faut plus de temps pour tourner autour de son propre axe que toute autre planète du Système solaire112,106. Comme Uranus, elle possède une rotation rétrograde et tourne sur elle-même dans le sens opposé à celui des autres planètes : le soleil s'y lève à l'ouest et se couche à l'est112. Vénus possède l'orbite la plus circulaire des planètes du Système solaire, son excentricité orbitale étant presque nulle, et, du fait de sa lente rotation, est quasiment sphérique (aplatissement considéré comme nul)112. Elle ne possède pas de satellite naturel94. En revanche, à l'instar de celui de la Terre, Vénus est accompagnée sur son orbite par un anneau, disque de poussières circumsolaire très peu dense.`
  },
  {
      name: "Terre",
      size: "12 756 kms",
      spitch: `La Terre (1 ua) est la plus grande (12 756 km de diamètre) et la plus massive des planètes telluriques ainsi que la plus dense du Système solaire113,114. Elle est notamment le seul objet céleste connu pour abriter la vie115,116. Elle orbite autour du Soleil en 365,256 jours solaires — une année sidérale — et réalise une rotation sur elle-même relativement au Soleil en 23 h 56 min 4 s — un jour sidéral — soit un peu moins que son jour solaire de 24 h du fait de ce déplacement autour du Soleil117. L'axe de rotation de la Terre possède une inclinaison de 23°, ce qui cause l'apparition de saisons118,113.

      La Terre possède un satellite en rotation synchrone autour d'elle, la Lune, le seul satellite significativement grand d'une planète tellurique dans le Système solaire115,119. Selon l'hypothèse de l'impact géant, ce satellite s'est formé à la suite d'une collision de la proto-Terre avec un impacteur de la taille de la planète Mars (nommé Théia) peu après la formation de la planète il y a 4,54 milliards d'années36,119,120. L'interaction gravitationnelle avec son satellite crée les marées, stabilise son axe de rotation et réduit graduellement sa vitesse de rotation36,119. La planète évolue également dans un disque de poussière autour du Soleil121.
      
      Son enveloppe rigide — appelée la lithosphère — est divisée en différentes plaques tectoniques qui migrent de quelques centimètres par an122. Environ 71 % de la surface de la planète est couverte d'eau liquide — fait unique parmi les planètes telluriques, avec notamment des océans, mais aussi des lacs et rivières, constituant l'hydrosphère — et les 29 % restants sont des continents et des îles, tandis que la majeure partie des régions polaires est couverte de glace93,122. La structure interne de la Terre est géologiquement active, le noyau interne solide et le noyau externe liquide (composés tous deux essentiellement de fer) permettant notamment de générer le champ magnétique terrestre par effet dynamo et la convection du manteau terrestre (composé de roches silicatées) étant la cause de la tectonique des plaques, activité qu'elle est la seule planète à connaître119. L’atmosphère terrestre est radicalement différente de celle des autres planètes, car elle a été altérée par la présence de formes de vie jusqu'à contenir de nos jours 21 % d’oxygène103,115,117. Celle-ci augmente également la température moyenne de 33 kelvins par effet de serre, la faisant atteindre 288 K (15 °C) et permettant l'existence d'eau liquide115.`
  },
  {
      name: "Mars",
      size: "6779 kms",
      spitch: `Mars (1,5 ua) est deux fois plus petite que la Terre et Vénus, et fait seulement environ le dixième de la masse terrestre123,124,125. Sa période de révolution autour du Soleil est de 687 jours terrestres et sa journée dure 24 heures et 39 minutes97,125. La période de rotation de Mars est du même ordre que celle de la Terre et son obliquité lui confère un cycle des saisons similaire au cycle terrestre. Ces saisons sont toutefois marquées par une excentricité orbitale cinq fois et demie plus élevée que celle de la Terre, d'où une asymétrie saisonnière sensiblement plus prononcée entre les deux hémisphères et un climat qui peut être qualifié d'hyper-continental : en été, la température dépasse rarement les 20 à 25 °C à l'équateur, alors qu'elle peut chuter jusqu'à −120 °C, voire moins pendant l'hiver aux pôles97,125.

      Elle possède une atmosphère ténue, principalement composée de dioxyde de carbone, et une surface désertique caractérisée visuellement par sa couleur rouge, due à l'abondance d'hématite amorphe ou oxyde de fer(III)126,127. Sa topographie présente des analogies aussi bien avec la Lune, par ses cratères et ses bassins d'impact en raison de sa proximité avec la ceinture d'astéroïdes93, qu'avec la Terre, par des formations d'origine tectonique et climatique telles que des volcans, des rifts, des vallées, des mesas, des champs de dunes et des calottes polaires127,128. Le plus haut volcan du Système solaire, Olympus Mons (qui est un volcan bouclier), et le plus grand canyon, Valles Marineris, se trouvent sur Mars127129,130. Ces structures géologiques montrent des signes d’une activité géologique, voire hydraulique, qui a peut-être persisté jusqu’à récemment, mais qui est presque totalement arrêtée de nos jours131,132 ; seuls des événements mineurs surviendraient encore épisodiquement à sa surface, tels que des glissements de terrain ou de rares éruptions volcaniques sous forme de petites coulées de lave128. La planète est par ailleurs dépourvue de champ magnétique global128.
      
      Mars possède deux très petits satellites naturels de quelques dizaines de kilomètres de diamètre, Phobos et Déimos, qui pourraient être des astéroïdes capturés, mais le consensus actuel privilégie une formation à la suite d'un choc avec la planète en raison de leur faible éloignement à la planète133,125,127. Ceux-ci sont en rotation synchrone — montrant donc toujours la même face à la planète — mais, du fait des forces de marée avec la planète, l'orbite de Phobos diminue et le satellite se décomposera lorsqu'il aura franchi la limite de Roche, tandis que Déimos s'éloigne progressivement134.`  
  },
  {
      name: "Jupiter",
      size: "143 000 kms",
      spitch: `Jupiter (5,2 ua), par ses 317 masses terrestres, est aussi massive que 2,5 fois toutes les autres planètes réunies et son diamètre avoisine les 143 000 kilomètres40,157. Sa période de révolution est d'environ 12 ans et sa période de rotation est d'un peu moins de 10 heures158,40,159.

      Elle est composée essentiellement d'hydrogène et d'hélium, d'un peu d'ammoniac et de vapeur d'eau ainsi que probablement un noyau solide rocheux, mais n'a pas de surface définie158,160. Sa forte chaleur interne anime des vents violents, de près de 600 km/h, qui parcourent les couches supérieures de l'atmosphère de la planète et la divisent visiblement en plusieurs bandes colorées à différentes latitudes, séparées par des turbulences158161. Ce phénomène crée également un certain nombre de caractéristiques semi-permanentes, comme la Grande Tache rouge, un anticyclone observé depuis au moins le xviie siècle158,162. Sa puissante magnétosphère, animée par un courant électrique dans sa couche interne d'hydrogène métallique, crée un des plus forts champ magnétique connu du Système solaire — dépassé seulement par les taches solaires — et des aurores polaires aux pôles de la planète160. Si la température au niveau des nuages est d'environ 120 K (−153 °C), elle augmente rapidement avec la pression vers le centre de la planète du fait de la compression gravitationnelle et atteindrait 6 000 K et une pression un million de fois plus élevée que celle sur Terre à 10 000 km de profondeur160,158.
      
      Jupiter possède 79 satellites connus40. Les quatre plus gros, aussi appelés satellites galiléens car découverts par l'astronome italien Galilée au xviie siècle, Ganymède, Callisto, Io et Europe, présentent des similarités géologiques avec les planètes telluriques35,158,163. Parmi les plus grands objets du Système solaire — ils sont tous plus grands que les planètes naines —, Ganymède est même la plus grande et la plus massive lune du Système solaire, dépassant en taille la planète Mercure35,159,158. Par ailleurs, les trois lunes intérieures, Io, Europe et Ganymède, sont le seul exemple connu de résonance de Laplace du Système solaire : les trois corps sont en résonance orbitale 4:2:1, ce qui a un impact sur leur géologie et par exemple le volcanisme sur Io35,50,159,163.
      
      Le système jovien comprend également les anneaux de Jupiter, mais l'influence de la planète s'étend à de nombreux objets du Système solaire, comme les astéroïdes troyens de Jupiter35,162.`
  },
  {
      name: "Saturne",
      size: "121 000 kms",
      spitch: `Saturne (9,5 ua) possède des caractéristiques similaires à Jupiter, telles que sa composition atmosphérique et sa puissante magnétosphère164,165. Bien qu'elle fasse 60 % du volume de l'autre planète géante gazeuse du fait de son diamètre équatorial d'environ 121 000 kilomètres, elle est beaucoup moins massive avec 95 masses terrestres166,41. Sa période de révolution vaut un peu moins de 30 années tandis que sa période de rotation est estimée à 10 h 33 min41,167.

      La caractéristique la plus célèbre de la planète est son système d'anneaux proéminent35,166,168. Composés principalement de particules de glace et de poussières, et divisés en sections espacées de divisions, ils se seraient formés il y a moins de 100 millions d'années166,169. De plus, elle est la planète possédant le plus grand nombre de satellites naturels, 82 étant confirmés et des centaines de satellites mineurs garnissant son cortège41. Sa plus grande lune, Titan, est également la deuxième plus grande du Système solaire et est la seule lune connue à posséder une atmosphère substantielle35,166,170. Une autre lune remarquable, Encelade, émet de puissants geysers de glace du fait de son cryovolcanisme et serait un habitat potentiel pour la vie microbienne35,166,171.
      
      Seule planète du Système solaire moins dense que l'eau41, l'intérieur de Saturne est très probablement composé d'un noyau rocheux de silicates et de fer entouré de couches constituées en volume à 96 % d'hydrogène qui est successivement métallique puis liquide puis gazeux, mêlé à de l'hélium166,41,164. Un courant électrique dans la couche d'hydrogène métallique donne naissance à sa magnétosphère, la deuxième plus grande du Système solaire, mais beaucoup plus petite que celle de Jupiter, et à des aurores polaires164. L'atmosphère de Saturne est généralement terne et manque de contraste, bien que des caractéristiques de longue durée puissent apparaître tel l'hexagone à son pôle nord172. Les vents sur Saturne peuvent atteindre une vitesse de 1 800 km/h, soit les deuxièmes plus rapides du Système solaire après ceux de Neptune172.`
  },
  {
      name: "Uranus",
      size: "51 000 kms",
      spitch: `Uranus (19,2 ua) est la moins massive des planètes géantes, par ses 14 masses terrestres173,174,175. Son diamètre d'environ 51 000 kilomètres est légèrement supérieur à celui de sa presque jumelle Neptune, en raison de la compression gravitationnelle de cette dernière176. Sa période de révolution est d'environ 84 ans et, caractéristique unique parmi les planètes du Système solaire, elle orbite le Soleil sur son côté en un peu plus de 17 heures, son axe de rotation étant pratiquement dans son plan de révolution, donnant l'impression qu'elle « roule » sur le plan de l'écliptique173,175,176. Ses pôles Nord et Sud se trouvent donc là où la plupart des autres planètes ont leur équateur. La planète est pourvue d'une magnétosphère vrillée du fait de cette inclinaison de l'axe177,175.

      Comme celles de Jupiter et Saturne, l'atmosphère d'Uranus est composée principalement d'hydrogène et d'hélium et de traces d'hydrocarbures178. Cependant, comme Neptune, elle contient une proportion plus élevée de « glaces » au sens physique, c'est-à-dire de substances volatiles telles que l'eau, l'ammoniac et le méthane, tandis que l'intérieur de la planète est principalement composé de glaces et de roches, d'où leur nom de « géantes de glaces »178. Par ailleurs, le méthane est le principal responsable de la teinte aigue-marine de la planète176. Son atmosphère planétaire est la plus froide du Système solaire, atteignant 49 K (−224 °C) à la tropopause, car elle rayonne très peu de chaleur dans l'espace, et présente une structure nuageuse en couches175. Cependant, la planète ne présente presque aucun relief à la lumière visible, comme les bandes de nuages ou les tempêtes associées aux autres planètes géantes, malgré des vents de l'ordre de 900 km/h178.
      
      Première planète découverte à l’époque moderne avec un télescope — par William Herschel en 1781 — et non connue depuis l'Antiquité, Uranus possède un système d’anneaux et de nombreux satellites naturels : on lui connaît 13 anneaux étroits et 27 lunes, les plus grandes étant Titania, Obéron, Umbriel, Ariel et Miranda ; cette dernière est notamment remarquable en raison de la grande varitété de terrains qu'elle présente35,173,179,176.`
  },
  {
      name: "Neptune",
      size: "49 500 kms",
      spitch: `Neptune (30 ua) est la planète la plus éloignée du Soleil connue au sein du Système solaire180,181,182. Légèrement plus massive qu'Uranus par ses 17 masses terrestres, mais plus petite, son diamètre équatorial étant d'environ 49 500 kilomètres par compression gravitationnelle, elle est en conséquence plus dense — faisant d'elle la planète géante la plus dense183,182. Sa période de révolution est d'environ 165 ans et sa période de rotation dépasse légèrement 16 heures180.

      N'étant pas visible à l'œil nu, elle est le premier objet céleste et la seule des huit planètes du Système solaire à avoir été découverte par déduction plutôt que par observation empirique, grâce aux perturbations gravitationnelles inexpliquées sur l'orbite d'Uranus : les calculs de l'astronome français Urbain Le Verrier permettent au prussien Johann Gottfried Galle de l'observer au télescope en 1846183,182. On lui connaît 14 satellites naturels dont le plus grand est Triton, qui est géologiquement actif et présente des geysers d'azote liquide184. Il s'agit par ailleurs du seul grand satellite du Système solaire situé sur une orbite rétrograde35,185. La planète possède en outre un système d'anneaux faible et fragmenté et une magnétosphère183,185, et est accompagnée sur son orbite de plusieurs planètes mineures, les astéroïdes troyens de Neptune186.
      
      L'atmosphère de Neptune est similaire à celle d'Uranus, composée principalement d'hydrogène et d'hélium, de traces d'hydrocarbures ainsi que d'une proportion plus élevée de « glaces » (eau, ammoniac et méthane), faisant d'elle la deuxième « géante de glaces »187. Par ailleurs, le méthane est partiellement responsable de la teinte bleue de la planète, mais l'origine exacte de son bleu azur reste encore inexpliquée187. Contrairement à l'atmosphère brumeuse et relativement sans relief d'Uranus, celle de Neptune présente des conditions météorologiques actives et visibles, notamment une Grande Tache sombre comparable à la Grande Tache rouge de Jupiter, présente au moment du survol de Voyager 2 en 1989183. Ces conditions météorologiques sont entraînées par les vents les plus forts connus du Système solaire, qui atteignent des vitesses de 2 100 km/h187. En raison de sa grande distance du Soleil, l'extérieur de son atmosphère est l'un des endroits les plus froids du Système solaire, les températures au sommet des nuages approchant 55 K (−218,15 °C)187.`
  }
];

module.exports = planets;